### PR TITLE
Colab Notebook (WIP)

### PR DESCRIPTION
**Pull request by afiaka87**
Hey I made a colab notebook to try and test this repo out on GPU. Seems to work on TPU in my testing which is good to know. Lots of commented out blocks currently as I mostly wanted to get the base notebook written out quickly. Feel free to use any/none of it.

https://github.com/afiaka87/dalle-lightning/blob/notebook/dalle_lightning.ipynb

@robvanvolt may have interest.

### CODE REVIEW

**Comment by afiaka87** [comment]
It currently downloads virtual genome from my dropbox. Might be better to grab something from academictorrents instead for long-term hosting.

**Comment by tgisaturday** [comment]
@afiaka87 thanks for the work! I've just finished refactoring and debugging vaes. Feel free to test them out if you like.

**Comment by afiaka87** [comment]
No problem @tgisaturday! Great codebase. Super clean. I'll hopefully be able to test out at least the GumbelVQGAN and the VQVAE2.

Are you getting good results with the vqvae2?

**Review by tgisaturday — APPROVED** [review]
@afiaka87 All vae types are tested with fake_data on tpus. Thanks again!

**Comment by robvanvolt** [comment]
> https://github.com/afiaka87/dalle-lightning/blob/notebook/dalle_lightning.ipynb

Though I got an Error (404 - Page not found) - is there a new link?:)

**Comment by afiaka87** [comment]
> > https://github.com/afiaka87/dalle-lightning/blob/notebook/dalle_lightning.ipynb
> 
> Though I got an Error (404 - Page not found) - is there a new link?:)

It's been merged into the codebase.

**Pull request merged**
